version: "3.9"
services:


  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=harisenin_project

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://root:root@postgres:5432/harisenin_project?sslmode=disable
      - PORT_APP=8080
      - DB_DSN=host=postgres user=root password=secret dbname=motivational_quote port=5432
      - APP_NAME=Beneboba-Tweets
      - TOKEN_SYMETRIC_KEY=msfwvvokev71979lkfoqjipld97802jw
      - GO_ENV=production
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET=tweets-harisenin-bucket
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
