### Localhost
GET http://localhost:8080
Accept: application/json
Content-Type: application/json


### Ping
POST http://54.91.18.165/ping
Accept: application/json
Content-Type: application/json


### Register
POST http://54.91.18.165:8080/api/user
Accept: application/json
Content-Type: application/json

{
  "username": "coba",
  "password": "beneboba"
}